title: "Javascript Learning"
url: "http://localhost:4000/javascript/js/lexical_environment"
subtitle: "Life flourishes with programming language learning"
banner: "http://localhost:4000/assets/img/learnings/javascript/header.png"
content_title: "Lexical Environment"
details:
    - title: "Definition"
      subsections:
          - text: |
              According to ECMAScript specification 262 (8.1): A Lexical Environment is a specification type used to define the association of Identifiers to specific variables and functions based upon the lexical nesting structure of ECMAScript code.
    - title: "What is it?"
      subsections:
          - text: |
              It means where something sits physically in the code you write. The location of what you write in the code is very important. Depending on the physical location of what you wrire in the code, its interpretation can be different. The "Lexical" means 'having to do with words or grammar'.

    
