title: "Tech Learning"
url: "https://soo1017.github.io/soolee/tech/javascript/lexical_environment"
subtitle: "Your life flourishes with everyday programming language learning"
banner: "https://soo1017.github.io/soolee/assets/img/learnings/javascript/header.png"
content_title: "Lexical Environment"
details:
    - title: "Definition"
      subsections:
          - text: |
              According to ECMAScript specification 262 (8.1): A Lexical Environment is a specification type used to define the association of Identifiers to specific variables and functions based upon the lexical nesting structure of ECMAScript code.

    #         images:
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen1.png"
    #               caption: Pick Your FaveU
    #               setname: screens
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen2.png"
    #               caption: Poke FaveU
    #               setname: screens
    #       - text: |
    #           A program that reads your code and determine what it does amd the validity of its grammar.
    #         images:
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen1.png"
    #               caption: Pick Your FaveU
    #               setname: screens
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen2.png"
    #               caption: Poke FaveU
    #               setname: screens
    - title: "What is it?"
      subsections:
          - text: |
              It means where something sits physically in the code you write. The location of what you write in the code is very important. Depending on the physical location of what you wrire in the code, its interpretation can be different. The "Lexical" means 'having to do with words or grammar'.
    #         images:
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen1.png"
    #               caption: Pick Your FaveU
    #               setname: screens
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen2.png"
    #               caption: Poke FaveU
    #               setname: screens
    #       - text: |
    #           A program that reads your code and determine what it does amd the validity of its grammar.
    #         images:
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen1.png"
    #               caption: Pick Your FaveU
    #               setname: screens
    #             - url: "https://soo1017.github.io/soolee/assets/img/projects/faveu/main_screen2.png"
    #               caption: Poke FaveU
    #               setname: screens

    
